### ISSUE TITLE
where is key.bat?

### ISSUE THREAD

**Issue by essivision** [vrtadmin/TeslaDecrypt#11]
Hi

I can't find `key.bat`. In your blog post you talk about key.bat, but I can't find it in github. My files inflicted to  CryptoWall 3.0 and generate me many html or txt file in my hard. my payment url is `xlowfznrg4wf7dli.onion/83ea04522b41e2`. how to decrypt my files with your tools?

thanks

**Comment by Demonslay335** [comment]
@essivision There is no solution for CryptoWall 3.0. This tool is specifically for the first variant of TeslaCrypt from over a year ago.
