### ISSUE TITLE
license

### ISSUE THREAD

**Issue by JoaquimFernando** [vrtadmin/TeslaDecrypt#12]
Hi.

We are a company from Portugal.
As a company can we downlad and use "Talos Universal TeslaDecrypter Version 1.0" in our Windows XP Service Pack 3 (32 bits) computers without any cost?

Can you give me the link where can i download the appropriate windows binary?

Best regards,
Joaquim Fernando
J. Ferreira - Contabilidades, Lda
PORTUGAL

**Comment by finchy** [comment]
You can find them here:

http://www.talosintelligence.com/teslacrypt_tool/

Also, yes, you may use them at no cost.
